export const defaultTrackData = {
  volume: -32,
  volumeMode: "static",
  panMode: "static",
  soloMuteMode: "static",
  pan: 0,
  soloMute: [false, false],
  fxNames: ["nofx", "nofx"],
  sends: [false, false],
  panelPosition: { x: 0, y: 0 },
  panelActive: true,
  panelSize: { width: "325px", height: "auto" },
  reverbMode: ["static", "static"],
  reverbBypass: [false, false],
  reverbMix: [0.5, 0.5],
  reverbPreDelay: [0.5, 0.5],
  reverbDecay: [0.5, 0.5],
  delayMode: ["static", "static"],
  delayBypass: [false, false],
  delayMix: [0.5, 0.5],
  delayTime: [1, 1],
  delayFeedback: [0.5, 0.5],
  pitchShiftMode: ["static", "static"],
  pitchShiftBypass: [false, false],
  pitchShiftMix: [0.5, 0.5],
  pitchShiftPitch: [5, 5],
};
