export const defaultTrackData = {
  volume: -32,
  volumeMode: ["static"],
  panMode: ["static"],
  soloMode: ["static"],
  muteMode: ["static"],
  pan: 0,
  mute: false,
  solo: false,
  fxNames: ["nofx", "nofx"],
  sends: [false, false],
  panelPosition: { x: 0, y: 0 },
  panelActive: true,
  panelSize: { width: "325px", height: "auto" },
  reverbMode: ["static", "static"],
  reverbBypass: [false, false],
  reverbMix: [0.5, 0.5],
  reverbPreDelay: [0.5, 0.5],
  reverbDecay: [0.5, 0.5],
  delayMode: ["static", "static"],
  delayBypass: [false, false],
  delayMix: [0.5, 0.5],
  delayTime: [1, 1],
  delayFeedback: [0.5, 0.5],
  pitchShiftMode: ["static", "static"],
  pitchShiftBypass: [false, false],
  pitchShiftMix: [0.5, 0.5],
  pitchShiftPitch: [5, 5],
};

export const defaultBusData = [
  {
    id: crypto.randomUUID(),
    name: "Bus 1",
    volume: -32,
    fxNames: ["nofx", "nofx"],
    reverbMode: ["static", "static"],
    reverbMix: [0.5, 0.5],
    reverbPreDelay: [0.5, 0.5],
    reverbDecay: [0.5, 0.5],
    reverbBypass: [false, false],
    delayMode: ["static", "static"],
    delayMix: [0.5, 0.5],
    delayTime: [1, 1],
    delayFeedback: [0.5, 0.5],
    delayBypass: [false, false],
    pitchShiftBypass: [false, false],
    pitchShiftMode: ["static", "static"],
    pitchShiftMix: [0.5, 0.5],
    pitchShiftPitch: [5, 5],
    panelPosition: { x: 0, y: 0 },
    panelSize: { width: "325px", height: "auto" },
    panelActive: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Bus 2",
    volume: -32,
    fxNames: ["nofx", "nofx"],
    reverbMode: ["static", "static"],
    reverbMix: [0.5, 0.5],
    reverbPreDelay: [0.5, 0.5],
    reverbDecay: [0.5, 0.5],
    reverbBypass: [false, false],
    delayMode: ["static", "static"],
    delayMix: [0.5, 0.5],
    delayTime: [1, 1],
    delayFeedback: [0.5, 0.5],
    delayBypass: [false, false],
    pitchShiftMode: ["static", "static"],
    pitchShiftBypass: [false, false],
    pitchShiftMix: [0.5, 0.5],
    pitchShiftPitch: [5, 5],
    panelPosition: { x: 0, y: 0 },
    panelSize: { width: "325px", height: "auto" },
    panelActive: true,
  },
];
